spring:
  profiles:
    active: local

spring.batch.job.names: ${job.name:NONE}
logging.level:
  org.springframework:
    #    jdbc.core.JdbcTemplate: DEBUG
    batch.item.database: DEBUG
---
spring:
  profiles: mysql
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/batch_test
      username: root
      password: 1234
      driver-class-name: com.mysql.jdbc.Driver